2024-07-27 10:08:35 - error_msg [__init__.py -line:25]: [31mERROR - fail to init CT2MC_pub[0m 
